apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-s3
parameters:
  bucket: messager-uploads
  csi.storage.k8s.io/node-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-publish-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: csi-s3-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  mounter: geesefs
  options: --memory-limit 1000 --dir-mode 0777 --file-mode 0666
provisioner: ch.ctrox.csi.s3-driver # Вот это мы изменили
reclaimPolicy: Delete
volumeBindingMode: Immediate