apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mablinov2704/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: BFF_INTERNAL_URL
          value: "http://dev-bff:8080"
        - name: BFF_URL
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
        