apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bff.yaml
  - frontend.yaml
  - message-service.yaml
  - migrate-messages.yaml
  - migrate-users.yaml
  - postgres.yaml
  #- s3-pvc.yaml
  - user-service.yaml
  - minio.yaml
  #- s3-secret.yaml
  #- s3-storageclass.yaml

configMapGenerator:
- name: messages-migrations-cm
  files:
  - ../../migrations/message-service/
- name: users-migrations-cm
  files:
  - ../../migrations/user-service/