apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
- postgres.yaml
- migrate-users.yaml
- migrate-messages.yaml
- user-service.yaml
- message-service.yaml
- bff.yaml
- frontend.yaml
- s3-pvc.yaml