apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-messages
spec:
  template:
    spec:
      containers:
      - name: goose
        image: ghcr.io/kukymbr/goose-docker:latest
        env:
        - name: GOOSE_DRIVER
          value: "postgres"
        - name: GOOSE_DBSTRING
          value: "postgres://user:password@dev-postgres:5432/messager?sslmode=disable"
        - name: GOOSE_MIGRATION_DIR
          value: "/migrations"
        volumeMounts:
        - name: sql-files
          mountPath: /migrations
      volumes:
      - name: sql-files
        configMap:
          name: messages-migrations-cm
      restartPolicy: OnFailure