apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../s3-storageclass.yaml 
  - ../../s3-secret.yaml       

namePrefix: dev-

commonLabels:
  environment: dev